FROM jwilder/nginx-proxy:latest

COPY nginx.tmpl /app/nginx.tmpl
COPY 4057724_www.turingjudge.com.key /app/4057724_www.turingjudge.com.key
COPY 4057724_www.turingjudge.com.pem /app/4057724_www.turingjudge.com.pem
